import React, { useRef, Suspense } from 'react';
import { motion, useScroll, useTransform, useSpring } from 'framer-motion';
import ThreeDHero from '../components/ThreeDHero';
import { useNavigate } from 'react-router-dom';
import './LandingPage.css';

// ─── Main Landing Page ───────────────────────────────────────────────────────

export default function LandingPage() {
  const navigate = useNavigate();
  const containerRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"]
  });

  const titleY = useTransform(scrollYProgress, [0, 0.2], [0, -100]);
  const titleOpacity = useTransform(scrollYProgress, [0, 0.15], [1, 0]);
  const bentoY = useTransform(scrollYProgress, [0.3, 0.6], [100, 0]);
  const bentoOpacity = useTransform(scrollYProgress, [0.3, 0.4], [0, 1]);

  return (
    <div className="landing-wrapper" ref={containerRef}>
      <ThreeDHero />

      {/* Hero UI */}
      <section className="hero-section">
        <motion.nav 
          className="navbar"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.5 }}
        >
          <div className="logo">ACCIDENT <span className="red">DETECTION</span></div>
          <div className="nav-actions">
            <button className="btn-secondary" onClick={() => navigate('/dashboard')}>Launch Dashboard</button>
          </div>
        </motion.nav>

        <motion.div 
          className="hero-main"
          style={{ y: titleY, opacity: titleOpacity }}
        >
          <motion.h1
            initial={{ opacity: 0, scale: 0.95, filter: 'blur(20px)' }}
            animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }}
            transition={{ duration: 1.2, ease: "circOut" }}
          >
            THE FUTURE OF <br />
            <span className="outline">ROAD SAFETY</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1, duration: 1 }}
          >
            HybridSafetyNet AI core processing 470,000 real UK accident records <br />
            to predict, detect, and protect in milliseconds.
          </motion.p>
          <motion.div 
            className="cta-group"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.5 }}
          >
            <button className="btn-primary" onClick={() => navigate('/dashboard')}>Analyze Feed</button>
            <button className="btn-outline" onClick={() => navigate('/map')}>Risk Map</button>
          </motion.div>
        </motion.div>

        <div className="scroll-indicator">
          <motion.div 
            className="indicator-line"
            animate={{ scaleY: [0, 1, 0], originY: [0, 0, 1] }}
            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
          />
          <span>EXPLORE MODULES</span>
        </div>
      </section>

      {/* Feature Section */}
      <section className="feature-section">
        <motion.div 
          className="bento-grid"
          style={{ y: bentoY, opacity: bentoOpacity }}
        >
          <div className="bento-card x-large">
            <span className="tag">Inference Engine</span>
            <h3>HybridSafetyNet v2.1</h3>
            <p>Advanced ensemble architecture combining BiLSTM-Attention with XGBoost meta-learners for 99.1% accuracy on UK motorways.</p>
          </div>
          <div className="bento-card medium">
            <span className="tag">Vision</span>
            <h3>YOLOv8 Core</h3>
            <p>Real-time visual detection with structured logging and automated Twilio escalation.</p>
          </div>
          <div className="bento-card medium">
            <span className="tag">Intelligence</span>
            <h3>Llama 3.3 Integration</h3>
            <p>Context-aware accident summaries and emergency response recommendations generated by our 70B parameter expert system.</p>
          </div>
        </motion.div>
      </section>

      <footer className="footer">
        <div className="footer-content">
          <p>© 2026 ACCIDENT DETECTION SYSTEM — SECURED END-TO-END</p>
          <div className="footer-links">
            <span>System Status: Online</span>
            <span>API: 2.4.0</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
